### ISSUE TITLE
Handle Job/Pod creation errors in mirrord-layer 

### ISSUE THREAD

**Issue by infiniteregrets** [metalbear-co/mirrord#112]
The Job/Pod creation in mirrord-layer while creating the agent could result in errors mentioned here https://docs.rs/kube/latest/kube/enum.Error.html and we should handle them instead of a panic.

**Comment by camerondurham** [comment]
Hi, Just saw this in TWIR 446. I'm interested in taking this issue if nobody else claims it. Thanks!

**Comment by infiniteregrets** [comment]
@camerondurham I have assigned you the issue, thanks!

**Comment by camerondurham** [comment]
Really sorry for not sending any updates. I haven't forgotten about this and will be able to work on it Friday.

**Comment by eyalb181** [comment]
No worries @camerondurham, let us know you need any help.

**Comment by eyalb181** [comment]
Actually, a few of us do use M1s. We're currently having trouble working with minikube, so we're relying on remote clusters to test, but otherwise, things seem to be working. If you can elaborate on where you ran into trouble we might be able to help.
And don't worry about making a big deal out of it - it's really important for us to make onboarding easier for new contributors, so if we're able to get some insights from your attempts, all the better.

**Comment by camerondurham** [comment]
The most basic dumb issue I was having was basically the same as this, compiling project in an arm based container on M1 and not able to build all the dependencies: https://github.com/metalbear-co/mirrord/discussions/135

```
Compiling frida-gum-sys v0.3.4
error[E0432]: unresolved import `_frida_g_object_unref`
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/frida-gum-sys-0.3.4/src/lib.rs:25:9
   |
25 | pub use _frida_g_object_unref as g_object_unref;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no external crate `_frida_g_object_unref`

For more information about this error, try `rustc --explain E0432`.
The following warnings were emitted during compilation:

warning: Frida gum devkit not found, downloading from https://github.com/frida/frida/releases/download/15.1.17/frida-gum-devkit-15.1.17-linux-arm64.tar.xz...

error: could not compile `frida-gum-sys` due to previous error
```

I think a possible solution was already mentioned for the compiling `frida-gum-sys` step: https://github.com/metalbear-co/mirrord/discussions/135#discussioncomment-2927799

I can try the suggestions from that discussion, I haven't yet but looks like someone else was already having those issues and working on some sharable resources for compiling which would be awesome.

What I tried already:

```
pip install frida-tools
wget https://github.com/frida/frida/releases/download/15.1.17/frida-gum-devkit-15.1.17-linux-arm64.tar.xz
tar xf frida-gum-devkit-15.1.17-linux-arm64.tar.xz

# this is almost definitely wrong, just trying to follow this without checking where these files should actually live https://lib.rs/crates/frida-gum-sys
mv frida* libfrida* /usr/local/
```

I was also thinking of manually trying to install the frida devkit (the steps for this dep I think: https://lib.rs/crates/frida-gum-sys) and setup in the dev container but not sure if that's a feasible solution...

In the meantime I can use GH codespaces or an x86 Linux VM where the project compiles just fine 😄. I think I can try playing around with the devcontainer project and see if I can add some [platform specific](https://docs.docker.com/engine/reference/builder/#from) build steps but no promises since idk if that will work yet!
