### ISSUE TITLE
imagePullSecrets support for agent Pod via CLI flag

### ISSUE THREAD

**Issue by funkswing** [metalbear-co/mirrord#1276]
The agent Pod created on the cluster should support `imagePullSecrets` to use private image registries such as Artifactory.

https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

Add a flag to `mirrord exec` to support `imagePullSecrets`, such as:

```
mirrord exec -i private.registry.io/metalbear-co/mirrord:3.34.0 --agent-image-pull-secret my-secret-name
```

To result in the resulting Job's Pod to have the required `imagePullSecret` for the private registry
```
imagePullSecrets:
    - name: my-secret-name
```

**Comment by eyalb181** [comment]
This was added in version 3.36.0 (currently available as CLI and in the VSCode marketplace, and should be available for IntelliJ within a day or two). Note that this configuration can only be set through the mirrord configuration file, rather than as a CLI argument. So in the above example, you can run it like so:
`mirrord exec -f <path-to-mirrord.json>`

Where mirrord.json contains:
```
{    
    "agent":{
        "image": "private.registry.io/metalbear-co/mirrord:3.34.0",
        "image_pull_secrets": [
            {
                "name": "my-secret-name"
            }
        ]
    }
}
```
