### ISSUE TITLE
Support pause with ephemeral containers

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#1358]

**Comment by eyalb181** [comment]
@t4lz Was this done?

**Comment by aviramha** [comment]
To pause from inside an ephemeral container, we need to share the PID namespace (we already do)
then
```
echo FROZEN > /proc/1/root/sys/fs/cgroup/freezer/freezer.state
```
I couldn't do it manually from cli, I assume it's because I need to `nsenter` to the relevant cgroup and I couldn't do it since `kubectl debug` doesn't allow you to specify capabilities (but from code you can, as we already do).

**Comment by aviramha** [comment]
When implementing this and testing, I found out that on Docker k8s we use cgroup2, which doesn't support having cgroup per type - for freezer for example so the above solution wouldn't work probably.
