### ISSUE TITLE
Test mirroring on mesh

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#1963]
Although this is now theoretically supported, we've already received two reports from users that couldn't use mirroring on mesh. Need to test mirroring on mesh and make sure it actually works - make sure to test both istio and linkerd.

**Comment by meowjesty** [comment]
Can you give me more details on what's not working? Language/framework, what they're trying to do?

I can replicate the failed behavior by using an unreal tcp communication just to trigger it, but would be helpful to have something closer to reality to test against it as well.

**Comment by aviramha** [comment]
@meowjesty Did you setup a mesh and it worked?

**Comment by meowjesty** [comment]
For people using **istio**, try setting `agent.network_interface` to `"lo"` (or your _loopback_  network interface equivalent). More info on the config [here](https://mirrord.dev/docs/overview/configuration/#agent-network_interface).

Looks like the issue is that we're sniffing on the wrong network interface for istio mesh, and the traffic we get there is encrypted (mTLS).

Working on a fix that doesn't require setting the `agent.network_interface` explicitly.

**Comment by meowjesty** [comment]
Capturing on `lo` should be the default now when we detect `istio`.
