### ISSUE TITLE
pause on ephemeral agent breaks

### ISSUE THREAD

**Issue by jorros** [metalbear-co/mirrord#2012]
### Bug Description

It seems that the container is not unpausing after stopping the debug session (using Rider). The first time it works (ephemeral agent + pause), but any subsequent attempt fails

### Steps to Reproduce

1. Run mirrord with pause and ephemeral agent, it should work the first time
2. Run it again, this time it should break and will only work again once the pod has been restarted

### Backtrace

```shell
│ "Timeout requesting for target container pause.",

[2m2023-10-18T11:46:09.106207Z[0m [31mERROR[0m [2mmirrord_kube::api[0m[2m:[0m Daemon sent log message Failed to pause target container: PauseFailedCgroup(CgroupV2Error(NoPidsFoundInCgroup))
```

### Your operating system and version

macOS 14

### Local process

dotnet

**Comment by aviramha** [comment]
This happened to me on docker runtime in CI but not on containerd - I assume it's something related to the Host OS +  container runtime. In the case of what I had in CI - we had a race condition where our cgroup was cleaned up by the host cgroup manager since we had a "rogue" one. This is quite tricky but I'd guess the first step is to reproduce it.

**Comment by aviramha** [comment]
btw, just to verify, you used the privileged flag right?

**Comment by jorros** [comment]
Yeah, running without that gives me an error about missing access rights.
