### ISSUE TITLE
Enable pattern defined pod target

### ISSUE THREAD

**Issue by Dill-Dall** [metalbear-co/mirrord#2128]
Cheers :)
Just been looking into mirrord and, thought I should have meanings already...

What do I want: 
Feature for pattern matched pod names.

Why:
Pods are auto suffixed, meaning the mirrord.config would need to be updated with a new pod every time

This is kind of relevant, especially when issue -> https://github.com/metalbear-co/mirrord-intellij/issues/219 exist. Where the plugin can't select pod interactively.
```
{
    "target": {
        "path": {
        # would like the option of defining  di-spring-boot-starter-.* 
        # and mirroring the first match, or mirroring all the matches.
            "pod": "di-spring-boot-starter-5c478ff597-c99pg"
        },
        "namespace": "di-spring-boot-starter"
    },
    "feature": {
        "network": {
            "incoming": {
                "mode": "steal",
                "http_filter": {
                    "header_filter": "X-Playground: thomas"
                }
            },
            "outgoing": true
        },
        "fs" : "read",
        "env" : true
    }

}
```
Caveat: I´m not sure how one cleanly does debugging when running multiple pods at the same time using mirrord. Can one mirror all the pods at the same time? So that one always catch the request?

**Comment by Razz4780** [comment]
Hi!

Seems to me that you can possibly target a deployment instead of the pod. When targeting a deployment, mirrord will impersonate a random pod belonging to it. Does this fix your issue?

About mirroring all of the pods at the same time - it is possible with the operator, which is part of the mirrord for Teams (licensed). When running mirrord with the operator, targeting a deployment does exactly this (mirrors all pods instead of a random one).

**Comment by Dill-Dall** [comment]
It sure did :) Now  I think I've been turned over to mirrord as the defacto k8s debugging tool.
