### ISSUE TITLE
Support R on MacOS (ARM64)

### ISSUE THREAD

**Issue by danielloader** [metalbear-co/mirrord#2186]
I've given Mirrord a go with an R application (just one of the demo applications hosted at https://github.com/rstudio/shiny-examples) - with the intention of working locally and mirroring the traffic from a kubernetes cluster back to my local environment. I'm using vscode but the issue exists with the CLI tool.

I'm using:
- MacOS 14.2
- M1 Pro (ARM64)
- R 4.1.3 
- VS Code 1.85.1

Reproduction steps:

1. Install R - [https://cran.r-project.org/bin/macosx/big-sur-arm64/base/R-4.1.3-arm64.pkg](https://cran.r-project.org/bin/macosx/big-sur-arm64/base/R-4.1.3-arm64.pkg)
2. Install Mirrord via homebrew as directed on quickstart
3. Execute `mirrord exec -- R` to just start the interactive REPL

```shell
$ mirrord exec -- R
⠉ mirrord exec
    ✓ Running on latest (3.84.1)!
    ✓ ready to launch process
      ✓ layer extracted
      ✓ operator not found
      ✓ agent pod created
      ✓ pod is ready                                                                                                                                              
Killed: 9
```

I'm not sure but it sounds like a SIP/signed binary patching issue but thought I'd raise it in case anyone else tries to use mirrord with R.

**Comment by aviramha** [comment]
Hi, thanks for reporting this.
This is indeed a SIP issue. The R binary doesn't have x64 binary, which is our fallback for when SIP patching - in most cases we don't have arm to fallback to (which is the case) since macOS ships with arm64e.
Implementation of fallback to arm64 when available shouldn't be too hard, would you put it as a blocker from your side?

**Comment by danielloader** [comment]
Glad there's an obvious cause. As to it being a blocker, in the strictest sense it's just flat out not working so I guess it counts - Not tried the x64 installation on MacOS with Rosetta2 - though I'm wondering if packaging would become a nightmare as I'm not sure if R looks towards the kernel to detect the uarch for package installation or the R hard coded values based on the installed variant. 

Is it worth leaving this issue open with an amended title to include the ARM64 aspect of the issue? 

As someone not familiar with how this problem is felt on the mirrord side I don't know if it's something even on the roadmap or feasible to fix so I'll defer to you as to what to do with the issue. Thanks for replying.

**Comment by aviramha** [comment]
I did a bit of testing, we can detect cpu at runtime using sysctl crate
then
```rs

    // since arm64 can run x64 binaries,
    // we need to know if we can use arm binaries or not by checking arch on runtime.
    fn get_runtime_arch() -> u32 {
        sysctl::Ctl::new("hw.cputype")
            .expect("Failed fetching cpu type")
            .value_string().expect("Failed parsing cpu type")
            .parse()
            .expect("Failed parsing cpu type")
    }

    // False = Intel, True = Apple Silicon.
    pub static RUNTIME_ARCH_IS_ARM: Lazy<bool> = Lazy::new(|| {
        let arch = get_runtime_arch();
        arch == macho::CPU_TYPE_ARM64
    });
```
need to change our code to support this case and should work :)

**Comment by t4lz** [comment]
#2187 should solve the case of R and similar cases.

However the code for fat binaries is still imperfect. I guess for fat binaries this issue would be a lot less common because I think usually the reason to have a fat binary would be to include an `x86_64` binary. So possible issues would be:
1. Fat binary without `x86_64` on `arm64` hardware, and we would not patch because we think we're on `x86_64`. - I think unlikely, but possible.
2. Fat binary on `arm64` hardware, and we would choose `x86_64` even though `arm64` is available - could easily happen. Not an error but suboptimal.

We could fallback to `arm64` if `x86_64` is not available, which would solve problem 1, but not 2. For 2 we would have to know the actual hardware in runtime.

I tried out the sysctl code and apparently `hw.cputype` is the cputype of the binary, not of the system, so in this case it is the same as using conditional compilation as we currently do.
Maybe [this crate called `heim`](https://docs.rs/heim/latest/heim/host/struct.Platform.html#method.architecture) could give us the actual hardware architecture at runtime (via `uname`).
Alternatively, we could add an env var to the executionInfo with the CLI's binary's architecture. Theoretically it is possible to run the x86_64 binary of the CLI on an arm macbook and in that case we could make the suboptimal choice, but I can't really imagine why anyone would do that. We publish a single universal binary with both architectures and the arm one is chosen automatically, so it would actually take some work to do that. Also if the user went to some length to run our an `x86_64` binary maybe `x86_64` is a better choice anyways.

So I think the env var solution is the simplest and best (except if the plugins somehow run the `x86_64` cli when they call the universal binary, in that case that's not a god solution).

**Comment by danielloader** [comment]
Thanks for the work on this, can confirm ARM64 build of R 4.1 is working with mirrord exec!
