### ISSUE TITLE
Test mirroring in service mesh

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#2494]
We need to test mirroring with service mesh and update the docs accordingly. On a cluster with istio, check that mirroring works with HTTP1 and HTTP2, and with gRPC over HTTP1 and HTTP2.

**Comment by DmitryDodzin** [comment]
After some testing it seems that post update so mirroring interceptor listens to `lo` interface on meshed clusters (unless specified otherwise) both HTTP1.1 and HTTP2.0 traffic seem to mirror successfully.

I used the [yages](https://github.com/mhausenblas/yages) grpc echo server for tests + .net 8 c# implementation of said yages-schema.proto with rider + mirrord plugin to test out the mirroring. (easy deployment and supports grpc reflection for easy tests)

Haven’t tested grpc streaming api though it probably will have the same limitations as non meshed mirroring. Retrospectively the update so listener for mirroring would change to `lo` should have been added with update to iptables on stealing api to support mirroring because it's essentially the same problem.
