### ISSUE TITLE
Research sessions failing under high stress mirroring

### ISSUE THREAD

**Issue by DmitryDodzin** [metalbear-co/mirrord#2529]
There is sometimes a problem in running mirrord on high traffic/high throughput services where the required throughput of `mirrord-agent` -> `mirrord-int-proxy` is higher than available (via port-forward or operator connection) and the agent buffers start overflowing.

Possible solution is to allow http_filters (or some tcp filters like source_addr or something like that) to work somehow on mirroring or to have some sort of sampling of connections.

**Comment by aviramha** [comment]
I don't think that limiting the throughput is a solution since there's no real reason we wouldn't support such throughout - the only limitation should be resources and if those aren't the constraints then it should work

**Comment by Razz4780** [comment]
It seems to me that the problem originates in `TcpConnectionSniffer` sending data to all clients synchronously. In case one of the clients is not processing data quickly enough (or our agent-client connections don't handle the throughput in general), the sniffer blocks. Raw socket's recv queue grows and we start dropping IP packets.

What is a bit sad is that we cannot solve this problem entirely. There is no way (or at least no way I know of) we can apply back pressure to the connection sources, as we only sniff the incoming packets.

Proposed mitigations:
1. Use a separate `tokio::task` to receive packets from the raw socket. This way we can still discard packets that are for sure not interesting (e.g. not TCP, unsubscribed port, unknown TCP session), regardless of laggy clients. May help with the queue filling up with garbage.
2. When sending incoming data to the `TcpConnectionSniffer` client, require that the `mpsc` channel has capacity (use `Sender::try_send` instead of `Sender::send`). If the data cannot be sent instantly, close the connection for this client and send a log with warning.
3. Inspect [data offset](https://docs.rs/pnet_packet/latest/pnet_packet/tcp/struct.Tcp.html#structfield.data_offset) in intercepted TCP packets. This way we can discover dropped packets (holes in data) and close the connection for all clients.

@aviramha wdyt?

**Comment by aviramha** [comment]
I am not sure I understand where is the bottle neck exactly - perhaps we can use try_send and unwrap just to have a clear way of seeing which channel is hitting it's capacity?
Also, I am not entirely against making  the channel unbounded.

**Comment by Razz4780** [comment]
The first channel to hit capacity must be one of `sniffer -> client` data/new_conn channels. I don't think it's the `clients -> sniffer` channel, as processing its messages does not block (+ we shouldn't have many messages there, mostly port subscribe/unsubscribe).

> Also, I am not entirely against making the channel unbounded.

I don't think making the channel unbounded is the right way. It makes the agent prone to OOM due to buggy client apps. Given that in mfT the agent is shared and client apps are buggy (why use mirrord if not), I'm scared.

I'm thinking about using `tokio::broadcast` for sending incoming data from the sniffer to the clients. It offers non-blocking sending and lag-aware receiving (upon lag, client would send `TcpClose` to intproxy). It's capacity might be configurable in agent config (?)

**Comment by aviramha** [comment]
Ah right, I had this in mind also - broadcast is a good solution. I think in this case we should try to do optimizations that we can do, then see if we need to do more changes - broadcast should be fairly simple no?

**Comment by Razz4780** [comment]
> Ah right, I had this in mind also - broadcast is a good solution. I think in this case we should try to do optimizations that we can do, then see if we need to do more changes - broadcast should be fairly simple no?

Yup, not a complex change
