### ISSUE TITLE
Support DNS for Go apps

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#278]
Since Go resolves DNS over UDP, we need to support outgoing traffic over UDP in order to fully support Go apps. Note however that outgoing UDP doesn't need to work completely (within the scope of this issue), but only to the extent necessary for Go DNS to work.

**Comment by meowjesty** [comment]
Using what aviram said (for reference):

> I strace'd a Go binary - it simply does socket, connect, then sends data and receives data
it uses annoying primitives such as sendmsg and such but we shouldn't care if we do it like we do in tcp
socket gets created, socket calls connect -> instead of connecting to real socket, connect it to our endpoint then relay the data
need to hook recvfrom though so the address will make sense
