### ISSUE TITLE
Change many requests test to be less fragile

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#473]
Currently, the 'test_outgoing_traffic_many_requests' test makes a bunch of requests to different sites, and fails if even one request fails. We should change it to only fail if two or more requests (out of the 14) failed.

**Comment by t4lz** [comment]
Interesting, I hope this is not the return of https://github.com/metalbear-co/mirrord/issues/331. Will verify that before relaxing the test.

**Comment by t4lz** [comment]
Is this still needed, @eyalb181?

**Comment by t4lz** [comment]
Actually, there is [this run](https://github.com/metalbear-co/mirrord/actions/runs/3199607075/jobs/5225633728) that seems to me like there might be a bug in mirrord, not in the tests. Looks to me like the process crashed after mirrord got a RESET and stopped handling stuff. But we didn't get any of the output from [the code](https://github.com/metalbear-co/mirrord/pull/476/files#diff-d1ffc3ea3849a8606ecb8e2a900a1f4dd2da6b5087bfbd27ac6c1e32e6564cafR53-R63) I hoped would handle that kind of error in node. Maybe this error handling in node needs to be on the response instead of on the request.  Looking into it.

**Comment by t4lz** [comment]
https://github.com/metalbear-co/mirrord/issues/562
https://github.com/metalbear-co/mirrord/issues/564
Issues for some of the errors that sometimes cause this test to fail.

**Comment by eyalb181** [comment]
@t4lz Good call, closing
