### ISSUE TITLE
Test files are copied to the agent container in production

### ISSUE THREAD

**Issue by victorvianna** [metalbear-co/mirrord#474]
### Bug Description

I'm not a big docker user, but this line seems to suggest that tests are still taking up space in the container for a production environment.
https://github.com/metalbear-co/mirrord/blob/3795e759d42713cd97624f1ced62d7f0a31e8817/mirrord-agent/Dockerfile#L12

### Steps to Reproduce

N/A

### Your operating system and version

N/A

### Local process

N/A

**Comment by infiniteregrets** [comment]
I think tests are a part of the project workspace, which is why we need to copy them

**Comment by aviramha** [comment]
Hey Victor, Thanks for reporting it. As @infiniteregrets due to our workspace nature we have to have all workspace members as part of the compilation, never the less it still doesn't matter much as we do [multi stage build](https://docs.docker.com/build/building/multi-stage/). In our case, we have a build & run stages - build has the unneeded files, but it isn't shipped with the final image, only the binary that is the result of the build is copied.
