### ISSUE TITLE
Agent-only (DNS+network) mode

### ISSUE THREAD

**Issue by tamasfe** [metalbear-co/mirrord#574]
It's a bit of a niche, but there are occasions when I'd just like to access some service or services within the cluster with no container to impersonate.

Usually `k port-forward` is sufficient, however when domain names get involved (e.g. with multiple kafka brokers), it is just not enough.

It is currently possible to achieve this with mirrord, however one always has to find a pod to impersonate, even though the pod itself is not relevant.

I'd imagine something like this:

```sh
mirrord dns -n foo-namespace curl http://internal-service:1234
```

TODO:
- [x] Add the feature to mirrord.
- [x] #1351
- [x] https://github.com/metalbear-co/mirrord.dev/issues/72
- [x] #1375
- [x] #1376
- [x] https://github.com/metalbear-co/metalbear.co/issues/50

**Comment by t4lz** [comment]
> ```shell
> mirrord dns -n foo-namespace curl http://internal-service:1234
> ```

Here we're still executing some program, so I would say that `exec` should also be used for that new use-case. Maybe that mode could be enabled by a special `--target`? Maybe something like `--target cluster`? I think this functionality would also go well with the feature suggested in https://github.com/metalbear-co/mirrord/issues/567.

**Comment by eyalb181** [comment]
How about just not specifying a target?

**Comment by t4lz** [comment]
> How about just not specifying a target?

Yeah that would be the nicest for users that want to use this feature, but I thought using an explicit target might be nicer for users that actually do want to use a target but forgot to specify it. Another possible alternative is to have a `--no-target` flag.

**Comment by tamasfe** [comment]
> How about just not specifying a target?

This would feel natural to me, just typing `mirrord exec foo` would cause `foo` to "run inside" the cluster. I think omitting a target and a message at the beginning should be sufficient.

**Comment by t4lz** [comment]
My plan is to implement it in such a way that the agent is completely independent (could also run on a cluster that has no pods at all), but before I continue implementing it this way, I wanted to ask if anyone thinks we should instead choose an arbitrary target pod and use that pod if the user does not specify one. This second approach would mean less changes to the code, but would mean we do need an existing target pod.

**Comment by t4lz** [comment]
Ok, feedback from discord is that the agent should indeed be completely independent. So the next question is: we should not support an ephemeral agent and independent agent mode together, right? When users choose ephemeral agents, they must specify a target, yeah?

**Comment by aviramha** [comment]
> Ok, feedback from discord is that the agent should indeed be completely independent. So the next question is: we should not support an ephemeral agent and independent agent mode together, right? When users choose ephemeral agents, they must specify a target, yeah?

Yes - I don't see how ephemeral agent would make sense without a target ..

**Comment by t4lz** [comment]
The feature works in its branch already (but there is still some loose ends to close before merging), and now I'm working on saving the agent some work if it's a targetless agent (no iptables guard process, no sniffer thread, no stealer thread). My main motivation in making sure the agent does not do this extra work is not just performance, but also robustness - if we don't need the stealer and sniffer, why risk encountering errors over there.
But if you think we should support stealing incoming traffic from independent agents, please let me know and I'll make sure to only avoid the extra work when stealing (and mirroring) is disabled. I don't know if this is realistic, but I can imagine a scenario where the user's program first connects to some service, and then the service creates a new connection back to the program. Such a program would need to steal the incoming conneciton in order to work with an independent agent.
Also, if you think this should be split into another PR, please let me know, I can easily do that.

**Comment by aviramha** [comment]
> But if you think we should support stealing incoming traffic from independent agents

No, we shouldn't - at least not at the moment.
Need to create two follow up issues:
1. mirrord.dev docs
2. blog post
3. operator
