### ISSUE TITLE
VS code extentsion not working well with NVM

### ISSUE THREAD

**Issue by liaddrori1** [metalbear-co/mirrord#803]
### Bug Description

I use nvm to manage my node versions on my computer.

## Some background about nvm that I think is related:
The way NVM loads and manages node & npm versions are by using the .zshrc/.bashrc file, every time you load a shell, it reconfigures your node version. so without running the nvm script during shell creation, you will not find node & npm in your PATH.

## My bug:
When launching mirrord from the vs code ext, the process never starts and in my Kubernetes cluster, it tries to create many agent pods that are complete and deleted by the cluster. 
 
Endless pod creating by the job:
![image](https://user-images.githubusercontent.com/59142347/204787674-98b3f10c-9c59-45c7-8ad6-e0f32956a411.png)

The process never starts inside vs code:
![image](https://user-images.githubusercontent.com/59142347/204787961-496ea212-27b9-4b79-ad69-429102f78f3d.png)

**I think** that this is related to the mirrord process on my machine can't find node version (because NVM was not loaded)

When trying to lunch the vs code task (debug my node server), **without mirrord**, vs code knows which node & npm executables to use.

Example for vs code (Please note that vs code was able to find my executable):
![image](https://user-images.githubusercontent.com/59142347/204789128-280d0f97-0af5-413f-b121-acfa4263136f.png)

Also, You can specify to vs code which executable to use, when doing so, and setting it to `/home/liadd/.nvm/versions/node/v16.17.0/bin/node`, I was able to run it using mirrord, this let me think it's related to nvm.

I can't "hard-code" this option into my .vscode/launch.json file because other developers in my company may use different paths or they might manage their node without nvm

Furthermore, when running mirrord directly from zsh with this command `mirrord exec  --target deployment/manager node ./dist/index.js`, It does work, but in this shell NVM already loaded the node & npm configuration 

### Steps to Reproduce

1. Remove all previues node config
2. Install nvm and load into .zshrc/.bashrc
3. Launch using vs code extension with mirrod

### Your operating system and version

Ubuntu 20.10

### Local process

run with vscode

### Local process version

mirrord 3.12.0

**Comment by aviramha** [comment]
Thanks for the detailed reported! We will investigate and try to resolve it ASAP :)

**Comment by infiniteregrets** [comment]
hi @liaddrori1,

> I think that this is related to the mirrord process on my machine can't find node version (because NVM was not loaded)

do you see the see similar behavior when running with the CLI? perhaps the process you are running forks? which is why you see that many pods

> When trying to lunch the vs code task (debug my node server), without mirrord, vs code knows which node & npm executables to use.

I tried to reproduce the issue but wasn't able to. I had a homebrew installation for node, I uninstalled it and then installed nvm. Then ran `nvm install 17.0.0 && nvm use 17.0.0`. I ran with vscode after this and got this error message along the lines of "Cannot find runtime 'node' on PATH". In my launch.json, I set the `runtimeExecuteable` to "node" and that didn't seem to work either, with or without mirrord then I just removed the `runtimeExecuteable` and did `nvm default 17.0.0` and restarted vscode, everything seemed to work smoothly with/without mirrord. We don't really change anything related to which executable vscode picks, we just set the env for mirrord which includes the dylib responsible for talking to remote

> I can't "hard-code" this option into my .vscode/launch.json file because other developers in my company may use different paths or they might manage their node without nvm

understood, maybe they can leverage `runtimeExecuteable` in their launch.json and use the node they want to? since I am unable to reproduce it, I believe it just depends on how node is setup for the person locally 

> Furthermore, when running mirrord directly from zsh with this command mirrord exec --target deployment/manager node ./dist/index.js, It does work, but in this shell NVM already loaded the node & npm configuration

that makes sense, were you able to debug your process though?

**Comment by liaddrori1** [comment]
Fixed in 3.14.0
