### ISSUE TITLE
Select kubecontext / google cloud project

### ISSUE THREAD

**Issue by Chr1stian** [metalbear-co/mirrord#889]
I have the same namespace in multiple projects, mirrord only lets me see the namespace, so I have no idea what project I am picking from. Would be great to at least see the context, but optimally also change it directly in the UI.

**Comment by aviramha** [comment]
Interesting - mirrord uses the KUBECONFIG's context (like Kubectl) would it be okay if it changes it for you? Not only for the plugin, for example you'd change it in the UI and it will also apply in the cli

**Comment by Chr1stian** [comment]
Yes!

**Comment by aviramha** [comment]
I'm still trying to process and think how it's best done.
There are scenarios where mirrord (the "client") doesn't run on the local machine, but on a remote target (like WSL), so we should use the same contexts that mirrord would use, but then it's hard/problematic to keep it in sync (i.e you change it in the file, we don't get notified as mirrord client isn't always run)
We can run mirrord in the background, but it's problematic because we don't know what the remote would be.

This leads me to think we should have a `kubecontext` parameter in our `mirrord.json` configuration, and the default would be to use the current context that exists in the file, or it can be overriden using the configuration. 
The IntelliJ plugin would read the configuration file and show the chosen context, and if it's default it would show "kubectl's current"
wondering if it's good enough?

**Comment by Chr1stian** [comment]
As long as it shows clearly in the Intellij plugin when activating/using it would be fine for our usage

**Comment by aviramha** [comment]
We just released #1411 with 3.42.0, and you can have each mirrord configuration file with different kube config file.
Do you think it accomplishes the use case?
